# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97abf9fae8ccde48302e14536cee6c2ca8bcc17e36eee5de4bf49754dc9b568f3ac2d3cdf875f881b1f079c4b25efd7213b2fbc6aaf3dcaab3d5e946c8f17ff3

test:
  secret_key_base: 8812b7352e4031996faa61bd5f23c004b91fd7ad209659dee1b5612f6333a822dee428ef665d5792dd863789a794d6b28745605d8c86d47b249733b2eec51081

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
